INSERT INTO company_names (name, slug, status, created_at) VALUES ("ACI HealthCare Limited", "aci-healthcare-limited", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Active Fine Chemicals Ltd.", "active-fine-chemicals-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Ad-din Pharmaceuticals Ltd.", "ad-din-pharmaceuticals-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Adova Pharmaceuticals Ltd.", "adova-pharmaceuticals-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Advanced Chemical Industries Limited", "advanced-chemical-industries-limited", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Advent Pharma Ltd.", "advent-pharma-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("AFC Agro Biotech Ltd.", "afc-agro-biotech-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Al-Madina Pharmaceuticals Ltd.", "al-madina-pharmaceuticals-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Albion Animal Feed Products (Veterinary)", "albion-animal-feed-products-(veterinary)", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Albion Laboratories Ltd.", "albion-laboratories-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Albion Specialized Pharma Limited", "albion-specialized-pharma-limited", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Alco Pharma Limited", "alco-pharma-limited", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Alkad Laboratories", "alkad-laboratories", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Allied Pharmaceuticals Ltd.", "allied-pharmaceuticals-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Ambee Pharmaceuticals Ltd.", "ambee-pharmaceuticals-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Amico Laboratories Ltd.", "amico-laboratories-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Amulet Pharmaceuticals Ltd.", "amulet-pharmaceuticals-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("APC Pharma Limited", "apc-pharma-limited", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Apex Pharma Ltd.", "apex-pharma-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Apollo Pharmaceutical Laboratories Ltd.", "apollo-pharmaceutical-laboratories-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Arges Life Science Ltd.", "arges-life-science-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Aristopharma Limited", "aristopharma-limited", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Aristopharma Limited, Gazipur", "aristopharma-limited,-gazipur", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Army Pharma Limited", "army-pharma-limited", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Asiatic Laboratories Ltd.", "asiatic-laboratories-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Astra Biopharmaceuticals Ltd.", "astra-biopharmaceuticals-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Avarox Pharmaceuticals Ltd.", "avarox-pharmaceuticals-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Aztec Pharmaceuticals Ltd.", "aztec-pharmaceuticals-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Bangladesh Antibiotic Industries Limited", "bangladesh-antibiotic-industries-limited", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Beacon Cephalosporin Ltd.,", "beacon-cephalosporin-ltd.,", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Beacon Pharmaceuticals PLC", "beacon-pharmaceuticals-plc", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Belsen Pharmaceuticals Ltd.", "belsen-pharmaceuticals-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Bengal Drugs & Chemical Works Pharm. Ltd.", "bengal-drugs-&-chemical-works-pharm.-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Bengal Remedies Ltd.", "bengal-remedies-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Benham Pharmaceuticals Ltd.", "benham-pharmaceuticals-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Beximco Pharmaceuticals Ltd.", "beximco-pharmaceuticals-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Beximco Pharmaceuticals Ltd., Kaliakoir", "beximco-pharmaceuticals-ltd.,-kaliakoir", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Bexter Pharmaceuticals", "bexter-pharmaceuticals", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Biogen Pharmaceuticals Ltd.", "biogen-pharmaceuticals-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Biopharma Ltd.", "biopharma-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Bridge Pharmaceuticals Ltd.", "bridge-pharmaceuticals-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Bristol Pharma Ltd.", "bristol-pharma-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("C2C Pharma Limited", "c2c-pharma-limited", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Centeon Pharma Limited", "centeon-pharma-limited", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Central Pharmaceutical Ltd.", "central-pharmaceutical-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Chemist Laboratories Ltd.", "chemist-laboratories-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Cipla Ltd.", "cipla-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Concord Pharmaceuticals Ltd.", "concord-pharmaceuticals-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Cosmic Pharma Ltd.", "cosmic-pharma-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Cosmo Pharma Laboratories Ltd.", "cosmo-pharma-laboratories-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("DBL Pharmaceuticals Limited", "dbl-pharmaceuticals-limited", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Decent Pharma Laboratories Ltd.", "decent-pharma-laboratories-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Delta Pharma Limited", "delta-pharma-limited", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Desh Pharmaceuticals Ltd.", "desh-pharmaceuticals-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Dider Pharma Ltd.,", "dider-pharma-ltd.,", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Doctor Tims Pharmaceuticals Ltd.", "doctor-tims-pharmaceuticals-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Doctor's Chemicals Works Ltd.", "doctor's-chemicals-works-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Drug International Ltd.", "drug-international-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Drug International Ltd., Gopalpur", "drug-international-ltd.,-gopalpur", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Drug International Ltd., Squib Road", "drug-international-ltd.,-squib-road", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("EDCL (Bogra)", "edcl-(bogra)", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("EDCL (Dhaka)", "edcl-(dhaka)", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Edruc Ltd.", "edruc-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("EMCS Pharma Limited", "emcs-pharma-limited", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Eon Pharmaceuticals Ltd.", "eon-pharmaceuticals-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Eskayef Pharmaceuticals Ltd. Chandana, Gazipur", "eskayef-pharmaceuticals-ltd.-chandana,-gazipur", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Eskayef Pharmaceuticals Ltd. Mirpur.", "eskayef-pharmaceuticals-ltd.-mirpur.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Eskayef Pharmaceuticals Ltd., Narayanganj", "eskayef-pharmaceuticals-ltd.,-narayanganj", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Eskayef Pharmaceuticals Ltd., Tongi,Gazipur", "eskayef-pharmaceuticals-ltd.,-tongi,gazipur", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Ethical Drug Ltd.", "ethical-drug-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Euro Pharma Ltd.", "euro-pharma-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Everest Pharmaceuticals Ltd.", "everest-pharmaceuticals-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("FnF Pharmaceuticals Ltd.", "fnf-pharmaceuticals-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("G. A. Company Ltd.", "g.-a.-company-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("General Pharmaceuticals Ltd, Unit-2", "general-pharmaceuticals-ltd,-unit-2", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("General Pharmaceuticals Ltd.", "general-pharmaceuticals-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Gentry Pharmaceuticals Ltd.", "gentry-pharmaceuticals-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Genvio Pharma Ltd.", "genvio-pharma-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Get Well Limited", "get-well-limited", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Global Capsules Ltd.", "global-capsules-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Global Capsules Ltd., Gelatin Division", "global-capsules-ltd.,-gelatin-division", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Global Heavy Chemicals Ltd.", "global-heavy-chemicals-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Globe Pharmaceuticals Ltd.", "globe-pharmaceuticals-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Globex Pharmaceuticals Ltd.", "globex-pharmaceuticals-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Gonoshasthaya Basic Chemical Ltd.", "gonoshasthaya-basic-chemical-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Gonoshasthaya Pharmaceuticals Ltd.", "gonoshasthaya-pharmaceuticals-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Goodman Pharmaceuticals Ltd", "goodman-pharmaceuticals-ltd", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Greenland Pharmaceuticals Ltd.", "greenland-pharmaceuticals-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Guardian Healthcare Ltd.", "guardian-healthcare-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Healthcare Pharmaceuticals Ltd.", "healthcare-pharmaceuticals-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Hudson Pharmaceuticals Ltd.", "hudson-pharmaceuticals-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Ibn Sina Pharmaceutical Ind. Ltd.", "ibn-sina-pharmaceutical-ind.-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Incepta Pharmaceuticals Ltd.", "incepta-pharmaceuticals-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Incepta Pharmaceuticals Ltd. (Dhamrai Unit)", "incepta-pharmaceuticals-ltd.-(dhamrai-unit)", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Incepta Pharmaceuticals Ltd., Chemical Division", "incepta-pharmaceuticals-ltd.,-chemical-division", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Incepta Pharmaceuticals Ltd., Vaccine Division", "incepta-pharmaceuticals-ltd.,-vaccine-division", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Indo-Bangla Pharmaceuticals Ltd.", "indo-bangla-pharmaceuticals-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Islam Oxygen (Pvt) Ltd.", "islam-oxygen-(pvt)-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Jayson Pharmaceuticals Ltd.", "jayson-pharmaceuticals-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Jenphar Bangladesh Ltd.", "jenphar-bangladesh-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("JMI Industrial Gas Ltd.", "jmi-industrial-gas-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("JMI Syringes & Medical Devices Ltd.", "jmi-syringes-&-medical-devices-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("JP Pharmaceuticals (Veterinary)", "jp-pharmaceuticals-(veterinary)", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("JR Pharmaceuticals Ltd.", "jr-pharmaceuticals-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Kemiko Pharmaceuticals Ltd.", "kemiko-pharmaceuticals-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Kumudini Pharma Ltd.", "kumudini-pharma-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Labaid Pharmaceuticals Ltd.", "labaid-pharmaceuticals-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Leader Pharmaceuticals Limited", "leader-pharmaceuticals-limited", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Leon Pharmaceuticals Ltd.", "leon-pharmaceuticals-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Libra Infusion Limited", "libra-infusion-limited", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Linde Bangladesh Limited", "linde-bangladesh-limited", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Maks Drugs Ltd.", "maks-drugs-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Marksman Pharmaceutical Ltd.", "marksman-pharmaceutical-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Medicon Pharmaceuticals Ltd.", "medicon-pharmaceuticals-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Medimet Pharmaceuticals Ltd.", "medimet-pharmaceuticals-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("MedRx Life Science Ltd.", "medrx-life-science-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Millat Pharmaceuticals Ltd.", "millat-pharmaceuticals-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Modern Pharmaceuticals Ltd.", "modern-pharmaceuticals-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Momtaz Pharmaceuticals Ltd.", "momtaz-pharmaceuticals-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Monicopharma Limited", "monicopharma-limited", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("MSF Pharmaceuticals Ltd.,", "msf-pharmaceuticals-ltd.,", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("MST Pharma and Healthcare Ltd.", "mst-pharma-and-healthcare-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Mundipharma (Bangladesh) Pvt. Ltd.", "mundipharma-(bangladesh)-pvt.-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Mystic Pharmaceuticals Ltd.", "mystic-pharmaceuticals-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Naafco Pharma Ltd.", "naafco-pharma-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("National Drug Company Ltd.", "national-drug-company-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("National Laboratories Ltd.", "national-laboratories-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Navana Pharmaceuticals Ltd.", "navana-pharmaceuticals-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Newtec Pharmaceuticals Ltd.", "newtec-pharmaceuticals-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Nip Chemicals And Pharmaceuticals Ltd.", "nip-chemicals-and-pharmaceuticals-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Nipa Pharmaceuticals Ltd.", "nipa-pharmaceuticals-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("NIPRO JMI Company Ltd.", "nipro-jmi-company-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("NIPRO JMI Pharma Limited", "nipro-jmi-pharma-limited", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Novartis  (Bangladesh) Ltd.", "novartis--(bangladesh)-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Novatek Pharmaceuticals Ltd.", "novatek-pharmaceuticals-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Novo Healthcare and Pharma Ltd.", "novo-healthcare-and-pharma-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Novo Healthcare and Pharma Ltd. (Unit-2)", "novo-healthcare-and-pharma-ltd.-(unit-2)", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Novus Pharmaceuticals Ltd.", "novus-pharmaceuticals-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Nuvista Pharma Ltd", "nuvista-pharma-ltd", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("One Pharma Ltd.", "one-pharma-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Opsonin Bulk Drugs Ltd.", "opsonin-bulk-drugs-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Opsonin Pharma Limited", "opsonin-pharma-limited", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Orion Infusion Ltd.", "orion-infusion-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Orion Pharma Ltd.", "orion-pharma-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("OSL Pharma Ltd.", "osl-pharma-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Oyster Pharmaceuticals Ltd.", "oyster-pharmaceuticals-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Pacific Pharmaceuticals Ltd.", "pacific-pharmaceuticals-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Peertop Pharmaceuticals Ltd.,", "peertop-pharmaceuticals-ltd.,", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Peoples Pharma Ltd.", "peoples-pharma-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Pharmacil Ltd.", "pharmacil-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Pharmasia Ltd.", "pharmasia-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Pharmatek Chemicals Ltd.", "pharmatek-chemicals-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Pharmik Laboratories Ltd.", "pharmik-laboratories-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Physic Pharmaceuticals Ltd.,", "physic-pharmaceuticals-ltd.,", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Popular Pharmaceuticals PLC", "popular-pharmaceuticals-plc", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Premier Pharmaceuticals Ltd.", "premier-pharmaceuticals-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Prime Pharmaceuticals Ltd.", "prime-pharmaceuticals-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Pristine Chem Limited", "pristine-chem-limited", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Pristine Pharmaceuticals", "pristine-pharmaceuticals", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Promixco Pharmaceutical Ltd.", "promixco-pharmaceutical-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Purbadesh Chemists Ltd.,", "purbadesh-chemists-ltd.,", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Quality Pharmaceuticals (Pvt) Ltd.", "quality-pharmaceuticals-(pvt)-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Radiant Pharmaceuticals Ltd.", "radiant-pharmaceuticals-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Rahman Chemicals Ltd.", "rahman-chemicals-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Rampart-Power Bangladesh Ltd.", "rampart-power-bangladesh-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Rangs Pharmaceuticals Ltd.", "rangs-pharmaceuticals-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Reckitt Benckiser Bangladesh Ltd.", "reckitt-benckiser-bangladesh-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Reliance Pharmaceuticals Ltd.", "reliance-pharmaceuticals-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Reman Drug Laboratories Ltd.", "reman-drug-laboratories-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Remo Chemical Ltd.", "remo-chemical-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Renata Limited", "renata-limited", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Renata Limited, Gazipur", "renata-limited,-gazipur", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Renata Ltd., Bhaluka", "renata-ltd.,-bhaluka", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Rephco Pharmaceuticals Ltd.", "rephco-pharmaceuticals-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("RN Pharmaceuticals", "rn-pharmaceuticals", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Royal Pharmaceuticals Ltd.", "royal-pharmaceuticals-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("S. N. Pharmaceuticals Ltd.", "s.-n.-pharmaceuticals-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Save Pharmaceuticals Ltd.", "save-pharmaceuticals-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Seba Laboratories Ltd.", "seba-laboratories-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Sharif Pharmaceuticals Ltd.", "sharif-pharmaceuticals-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Shinil Pharma Limited", "shinil-pharma-limited", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Silco Pharmaceuticlas Ltd.", "silco-pharmaceuticlas-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Silva Pharmaceuticals Ltd.", "silva-pharmaceuticals-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("SMC Enterprise Limited", "smc-enterprise-limited", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Sodical Chemical Ltd.", "sodical-chemical-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Somatec Pharmaceuticals Ltd.", "somatec-pharmaceuticals-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Sonargaon Steel Fabricate Ltd., (Oxygen Plant)", "sonargaon-steel-fabricate-ltd.,-(oxygen-plant)", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Spectra International Ltd.,", "spectra-international-ltd.,", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Spectra Oxygen Limited", "spectra-oxygen-limited", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Square Cephalosporins Ltd.", "square-cephalosporins-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Square Formulations Ltd.", "square-formulations-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Square Lifesciences Limited, Pabna", "square-lifesciences-limited,-pabna", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Square Pharmaceuticals PLC, (Chemical Division)", "square-pharmaceuticals-plc,-(chemical-division)", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Square Pharmaceuticals PLC, Gazipur", "square-pharmaceuticals-plc,-gazipur", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Square Pharmaceuticals PLC, Pabna", "square-pharmaceuticals-plc,-pabna", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Standard Laboratories Ltd.", "standard-laboratories-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Sun Pharmaceutical (Bangladesh) Ltd.", "sun-pharmaceutical-(bangladesh)-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Sun Pharmaceuticals (EZ) Ltd., Narayanganj", "sun-pharmaceuticals-(ez)-ltd.,-narayanganj", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Sunman-Birdem Pharma Ltd.", "sunman-birdem-pharma-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Super Power Pharmaceuticals Ltd.", "super-power-pharmaceuticals-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Supreme Pharmaceuticals Ltd.", "supreme-pharmaceuticals-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Synovia Pharma PLC.", "synovia-pharma-plc.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Team Pharmaceuticals Ltd.", "team-pharmaceuticals-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Techno Drugs Ltd., BSCIC I/A, Narshingdi", "techno-drugs-ltd.,-bscic-i/a,-narshingdi", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Techno Drugs Ltd., Gazipur", "techno-drugs-ltd.,-gazipur", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Techno Drugs Ltd., Satipara, Narshingdi", "techno-drugs-ltd.,-satipara,-narshingdi", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("The ACME Laboratories Ltd.", "the-acme-laboratories-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("The White Horse Pharmaceuticals Ltd.", "the-white-horse-pharmaceuticals-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("UNIDO Pharmaceuticals Ltd.", "unido-pharmaceuticals-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Unimed Unihealth Pharmaceuticals Ltd.", "unimed-unihealth-pharmaceuticals-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Union Oxygen Limited", "union-oxygen-limited", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Union Pharmaceuticals Ltd.", "union-pharmaceuticals-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Unique Pharmaceutical Ltd.", "unique-pharmaceutical-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("United Chemicals & Pharmaceuticals Ltd.", "united-chemicals-&-pharmaceuticals-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Veritas Pharmaceuticals Ltd.", "veritas-pharmaceuticals-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Vion Pharmaceuticals (Veterinary)", "vion-pharmaceuticals-(veterinary)", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Virgo Pharmaceuticals Ltd.", "virgo-pharmaceuticals-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Vision Drugs Limited (Veterinary)", "vision-drugs-limited-(veterinary)", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("World API Chemical Industry Ltd.", "world-api-chemical-industry-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Zenith Pharmaceuticals Ltd.", "zenith-pharmaceuticals-ltd.", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Zhaofeng Gelating Limited", "zhaofeng-gelating-limited", 1, '2025-01-14 16:52:08');
INSERT INTO company_names (name, slug, status, created_at) VALUES ("Ziska Pharmaceuticals Ltd.", "ziska-pharmaceuticals-ltd.", 1, '2025-01-14 16:52:08');
